# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='update_interval',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
