# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0004_auto_20160915_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
