# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0005_auto_20160915_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='update_interval',
            field=models.PositiveIntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60)], default=10, help_text='Number of seconds between checks for content changes.'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='duration',
            field=models.PositiveIntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60)], default=10, help_text='Number of seconds the slide is displayed.'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='weight',
            field=models.SmallIntegerField(choices=[(-10, -10), (-9, -9), (-8, -8), (-7, -7), (-6, -6), (-5, -5), (-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, help_text='Relative ordering of slides. Higher values appear earlier in the list.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='Absolute path to video streaming URL.', verbose_name='Stream URL'),
        ),
    ]
